# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ICStTQeTo_GhFOXKPGdR6l9A7-Td_Ask
"""

!pip install transformers requests pandas

import pandas as pd
import requests
import time

df = pd.read_csv("Dataset.csv", encoding="latin-1", header=None)
df.columns = ["label", "text"]
print(f"Loaded {len(df)} rows")
print(df.head())

from transformers import pipeline

finbert = pipeline("text-classification", model="ProsusAI/finbert")
print("Model loaded!")

test = finbert("Apple reported record profits beating analyst expectations.")
print(test)

df = df.head(500)

labels, scores = [], []
for i, text in enumerate(df["text"]):
    result = finbert(text[:512])
    top = max(result, key=lambda x: x["score"])
    labels.append(top["label"])
    scores.append(round(top["score"], 4))
    if i % 50 == 0:
        print(f"Processed {i}/500...")

df["predicted_label"] = labels
df["confidence_score"] = scores
print("Done!")
print(df.head(10))

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Map labels to same format
df["label"] = df["label"].str.lower()
df["predicted_label"] = df["predicted_label"].str.lower()

acc = accuracy_score(df["label"], df["predicted_label"])
print(f"Accuracy: {acc:.4f}")
print("\nClassification Report:")
print(classification_report(df["label"], df["predicted_label"]))
print("Confusion Matrix:")
print(confusion_matrix(df["label"], df["predicted_label"], labels=["positive", "negative", "neutral"]))

df.to_csv("finbert_results.csv", index=False)
print("Saved!")

from google.colab import files
files.download("finbert_results.csv")

